server:
  port: 8002
  servlet:
    context-path: /ibes_test
  tomcat:
    max-http-post-size: -1
---
spring:
  profiles:
    active: local
    include:
      - core
      - database
      - web
  
  quartz:
    auto-startup: false
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        use_sql_comments: true
        show_sql: true
        format_sql: true

logging:
  file: ibes
  level:
    com.hiair.hom.ibes: debug
  
client:
  ticketagent:
#    address: http://localhost/kweb/webservice/helloworld
    address: http://localhost:8002/ibes_test/webserviceTest/helloworld
  
cxf:
  path: /webserviceTest

---
spring:
  profiles: local
  devtools:
    livereload:
      enabled: true
server:
  servlet:
    jsp:
      init-parameters:
        development: true
        
---
spring:
  profiles: dev

---    
spring:
  profiles: stage

---    
spring:
  profiles: prod